import React,{useState} from 'react';
import {useDataApp,useDashboardTabs,Filters,Dropdown,Slider,MetricCard,DataComponent,DataTable,EvidenceChart,Section,SortableRegion,SortableItem} from '../../data-app-public.jsx';
import {aggregate,scope,series,pairedChange,scenario,sum,money,exact,num,dateLabel,total} from './capital-data.js';
import './capital.css';
const tabs=[{id:'overview',label:'Visão do mercado',previousLabels:['Visão executiva']},{id:'portfolio',label:'Fundos',previousLabels:['Portfólio']},{id:'companies',label:'Detalhes do fundo',previousLabels:['Empresas e operações'],focusFields:['investment']},{id:'performance',label:'Histórico',previousLabels:['Desempenho']},{id:'scenarios',label:'Cenários'}].map(t=>({...t,filterIds:['universe','coverage','asOf']}));
const line={type:'line',x:'date',y:'nav',currency:'BRL',stackable:false,legend:{labels:{nav:'Patrimônio líquido',paid:'Capital integralizado',committed:'Capital comprometido'}},colors:{nav:'#168776',paid:'#4378be',committed:'#a57b35'},showXAxisLabel:false,showYAxisLabel:false};
const col=(field,label,format)=>({field,label,...(format?{renderCell:v=>format(v)}:{})});
const cols=[col('name','Fundo / classe'),col('id','CNPJ'),col('nav','Patrimônio líquido',money),col('reportingType','Tipo reportado'),col('coverage','Qualidade do PL')];
function Evidence({id,title,rows,children,sourceRows,queryId='portfolio',...rest}){return <DataComponent variant="card" id={id} queryId={queryId} title={title} sourceRows={sourceRows??rows} displayRows={rows} {...rest}>{children}</DataComponent>}
function Chart({id,title,rows,sourceRows,spec=line,height=290,description}){return <EvidenceChart variant="card" id={id} queryId="portfolio" title={title} rows={rows} sourceRows={sourceRows} spec={spec} height={height} description={description}/>}
function Metrics({rows,prefix='overview'}){const a=aggregate(rows),fip=rows[0]?.universe==='FIP';const metrics=[['nav','Patrimônio líquido reportado',money(a.nav),`${num(a.covered)} de ${num(a.count)} registros com PL`],['count','Fundos / classes',num(a.count),'CNPJs distintos nesta competência'],['paid',fip?'Capital integralizado':'Direitos creditórios',money(fip?a.paid:a.receivables),fip?'Valor informado pelos FIPs':'Com e sem aquisição substancial de riscos'],['committed',fip?'Capital comprometido':'Créditos inadimplentes',money(fip?a.committed:a.overdue),fip?'Valor informado pelos FIPs':'Campos I.2.a.3 + I.2.b.3; não inclui parcelas a vencer']];return <SortableRegion id={`${prefix}-metrics`} variant="freeform" className="cs-metrics" label="Indicadores">{metrics.map(([key,title,value,description])=><SortableItem key={key} id={`${prefix}-${key}`}><MetricCard id={`${prefix}-${key}`} queryId="portfolio" title={title} value={value} description={description} sourceRows={rows} displayRows={[a]}/></SortableItem>)}</SortableRegion>}
export function DashboardContent(){
 const shell=useDataApp();const {snapshot,queries,filters,setFilter,exploreDashboard,viewFocus,canReturnFromExploration,returnFromExploration}=shell;
 const {activeTabId}=useDashboardTabs(tabs);const tab=activeTabId??'overview';const [selected,setSelected]=useState('');const [shock,setShock]=useState(-10);
 const date=filters.asOf||'2026-04-30';const all=queries.portfolio.rows;const dates=[...new Set(all.map(r=>r.date))].sort();const universe=filters.universe==='FIDC'?'FIDC':'FIP';
 const history=scope(all,filters).filter(r=>r.date<=date);const rows=history.filter(r=>r.date===date);const a=aggregate(rows);const trend=series(history);const previousDate=dates[dates.indexOf(date)-1];const previous=history.filter(r=>r.date===previousDate);const paired=pairedChange(rows,previous);
 const ranking=rows.filter(r=>r.nav!==null).sort((a,b)=>b.nav-a.nav).slice(0,10);const focus=rows.find(r=>r.id===(viewFocus?.investment||selected))??ranking[0]??rows[0];const companyHistory=focus?history.filter(r=>r.id===focus.id):[];
 const drill=r=>{setSelected(r.id);exploreDashboard('companies',{filters,focus:{investment:r.id}})};
 const audited=queries.quality.rows.filter(r=>r.date===date&&r.universe.startsWith(universe));const missing=rows.filter(r=>r.nav===null);const negative=rows.filter(r=>r.nav!==null&&r.nav<0);const simulated=scenario(rows,shock);const simulatedCovered=simulated.filter(r=>r.scenarioNav!==null);const base=sum(simulatedCovered,'nav');const stressed=total(simulatedCovered,'scenarioNav');
 return <div className="cs-page">
  <div className="cs-context"><span className="cs-pill">DADOS PÚBLICOS · CVM</span><span>FIPs e FIDCs brasileiros · BRL · posições selecionadas</span><a href="#method">Fontes e metodologia ↗</a></div>
  <Filters sticky filters={snapshot.filters.filter(f=>f.id==='coverage')} queries={queries} values={filters} onChange={setFilter}><Dropdown label="Universo" value={universe} choices={['FIP','FIDC']} onChange={v=>setFilter('universe',v)} formatChoice={v=>v==='FIP'?'Participações · FIP':'Crédito · FIDC'} showLabel/><Dropdown label="Competência" value={date} choices={dates} onChange={v=>setFilter('asOf',v)} formatChoice={dateLabel} showLabel/></Filters>
  <p className="cs-note cs-boundary">{universe==='FIP'?'Participações: a base não classifica os fundos em VC, Growth ou PE. Não há atribuição automática por nome.':'Direitos creditórios: FIDC é um recorte de crédito estruturado, não representa todo o mercado de Private Credit.'} Dados agregados de fundos; sem detalhamento das empresas investidas.</p>
  {!rows.length?<div className="cs-empty"><h2>Nenhum registro neste recorte</h2><button className="cs-button" onClick={()=>setFilter('coverage','all')}>Limpar filtro de qualidade</button></div>:<>
  {tab==='overview'&&<>
   <Metrics rows={rows}/>
   <Section columns={2} spacing="after-metrics"><Chart id="capital-evolution" title="PL agregado nas competências selecionadas" rows={trend} sourceRows={history} description="O universo reportante muda entre datas. Variação de PL não é rentabilidade."/><Evidence id="coverage-card" title="Cobertura e comparação" rows={rows}><div className="cs-capital" data-reviewed-rows><span>CNPJs com PL nas duas últimas posições do recorte</span><strong>{num(paired.count)}</strong><p>{previousDate?`${dateLabel(previousDate)} → ${dateLabel(date)}`:'Sem competência anterior neste histórico'}</p><dl className="cs-facts"><div><dt>PL da base comparável anterior</dt><dd>{previousDate?money(paired.before):'—'}</dd></div><div><dt>PL da mesma base na posição atual</dt><dd>{previousDate?money(paired.after):'—'}</dd></div><div><dt>Variação de PL, não retorno</dt><dd>{previousDate?money(paired.after-paired.before):'—'}</dd></div></dl></div></Evidence></Section>
   <Section columns={2}><Evidence id="largest-funds" title="Maiores fundos / classes por PL · top 10" rows={ranking}><div className="cs-real-ranking" data-reviewed-rows>{ranking.map((r,i)=><button key={r.id} onClick={()=>drill(r)}><span className="cs-rank">{String(i+1).padStart(2,'0')}</span><span>{r.name}<small>{r.id}</small></span><strong>{money(r.nav)} ↗</strong></button>)}</div></Evidence><Evidence id="quality-summary" title="Qualidade da posição selecionada" rows={rows}><dl className="cs-facts" data-reviewed-rows><div><dt>PL não informado</dt><dd>{num(missing.length)}</dd></div><div><dt>PL negativo preservado</dt><dd>{num(negative.length)}</dd></div><div><dt>Linhas originais representadas</dt><dd>{num(sum(rows,'sourceRows'))}</dd></div></dl><p className="cs-note">Linhas de subclasses com valores iguais são consolidadas. Grupos com valores conflitantes são excluídos; consulte as ocorrências abaixo.</p><p className="cs-note">Somas reportadas podem conter investimento de um fundo em outro. Não representam capital econômico sem dupla contagem.</p></Evidence></Section>
  </>}
  {tab==='portfolio'&&<Evidence id="portfolio-register" title={`Explorar ${universe}s por nome ou CNPJ`} rows={rows}><DataTable rows={rows} columns={cols} caption="Fundos e classes da CVM" rowKey="id" onRowSelect={drill} rowActionLabel={r=>`Abrir ${r.name}`}/></Evidence>}
  {tab==='companies'&&focus&&<>
   <div className="cs-detail-controls">{canReturnFromExploration&&<button className="cs-button" onClick={returnFromExploration}>← Voltar à análise</button>}<button className="cs-button" onClick={()=>exploreDashboard('portfolio',{filters})}>Buscar outro fundo</button></div>
   <Evidence id="fund-profile" title={focus.name} rows={[focus]}><div className="cs-profile" data-reviewed-rows><div><span className="cs-pill">{focus.reportingType}</span><h2>{focus.id}</h2><p>Competência {dateLabel(focus.date)} · {focus.coverage}</p>{focus.admin&&<p>Administrador: {focus.admin}</p>}</div><div><small>Patrimônio líquido reportado</small><strong>{money(focus.nav)}</strong></div></div></Evidence>
   <Section columns={2}><Chart id="fund-history" title="Histórico do patrimônio líquido" rows={companyHistory} sourceRows={companyHistory}/><Evidence id="fund-values" title="Valores do informe" rows={[focus]}><dl className="cs-facts" data-reviewed-rows>{(universe==='FIP'?[['Capital comprometido',focus.committed],['Capital integralizado',focus.paid],['Investimento em cotas de FIP',focus.fundHoldings]]:[['Ativo total',focus.assets],['Direitos creditórios',focus.receivables],['Créditos inadimplentes',focus.overdue]]).map(([k,v])=><div key={k}><dt>{k}</dt><dd>{money(v)}</dd></div>)}</dl><p className="cs-note">Não são calculados TIR, TVPI ou múltiplos de retorno: os arquivos usados não fornecem os fluxos completos necessários.</p></Evidence></Section>
   <Evidence id="fund-history-table" title="Posições disponíveis para este CNPJ" rows={companyHistory}><DataTable rows={companyHistory} columns={[col('date','Competência',dateLabel),col('nav','PL',exact),...(universe==='FIP'?[col('paid','Integralizado',exact),col('committed','Comprometido',exact)]:[col('receivables','Direitos creditórios',exact),col('overdue','Inadimplentes',exact)])]} caption="Histórico reportado" searchable={false}/></Evidence>
  </>}
  {tab==='performance'&&<>
   <Chart id="historical-nav" title="Evolução do PL reportado" rows={trend} sourceRows={history}/>
   <Section><Evidence id="historical-coverage" title="Patrimônio e cobertura por competência" rows={trend} sourceRows={history}><DataTable rows={trend} columns={[col('date','Competência',dateLabel),col('count','Fundos / classes',num),col('covered','Com PL',num),col('nav','PL agregado',money),...(universe==='FIP'?[col('paid','Capital integralizado',money)]:[col('receivables','Direitos creditórios',money)])]} caption="Cobertura histórica" searchable={false}/><p className="cs-note">Amostras transversais: entradas, saídas, migrações de classes e exclusões de qualidade mudam a composição. Não interpolamos períodos ausentes nem tratamos crescimento patrimonial como retorno.</p></Evidence></Section>
  </>}
  {tab==='scenarios'&&<Section title="Sensibilidade exploratória" id="scenario-title" spacing="none" columns={2}>
   <Evidence id="scenario-inputs" title="Hipótese sobre os dados reais" rows={rows}><p className="cs-note">{universe==='FIP'?'Variação uniforme sobre o PL informado. Não é avaliação das empresas investidas.':'Redução hipotética dos direitos creditórios, descontada do PL, mantendo passivos constantes. Não é previsão de perda.'} Sem probabilidades, liquidez, taxas ou efeito de prazo.</p><div className="cs-sliders"><Slider label={universe==='FIP'?'Variação do PL (%)':'Redução dos direitos creditórios (%)'} min={universe==='FIP'?-50:0} max={50} step={5} value={universe==='FIP'?shock:Math.abs(shock)} onChange={setShock} formatValue={v=>`${v}%`}/><button className="cs-button" onClick={()=>setShock(0)}>Zerar choque</button></div></Evidence>
   <Evidence id="scenario-results" title="Resultado hipotético no recorte" rows={simulatedCovered} sourceRows={rows}><div className="cs-capital" data-reviewed-rows><span>Patrimônio líquido no cenário</span><strong>{money(stressed)}</strong><p>{money(stressed===null?null:stressed-base)} em relação à base de {money(base)}</p><p>{num(simulatedCovered.length)} de {num(rows.length)} registros possuem os campos necessários. Valores ausentes não são substituídos por zero.</p></div></Evidence>
  </Section>}
  </>}
  <details id="method" className="cs-method"><summary>Fontes, exclusões e limites</summary><p>Fonte: dados abertos CVM, licença ODbL. Extração: {new Date(snapshot.generatedAt).toLocaleDateString('pt-BR')}. Posições: abril, agosto e dezembro de 2025 e abril de 2026. FIP: informe quadrimestral; FIDC: meses selecionados do informe mensal. Esta seleção não representa a atualização mais recente disponível.</p><p>Chave: universo + CNPJ do fundo/classe + competência. Valores repetidos por subclasses não são somados. Grupos conflitantes e junções ambíguas são excluídos. Valores ausentes são mantidos como ausentes. PL negativo é preservado. Nomes refletem o informe na competência escolhida.</p><p>VC, Growth e PE não são classificados sem documentação adicional das gestoras. Sem dados de receita, EBITDA, participações ou rodadas das empresas. O BI acompanha universos regulatórios, não uma carteira única de investimentos. Nenhum registro financeiro sintético alimenta os indicadores.</p><p><a href="https://dados.cvm.gov.br/dataset/fip-doc-inf_quadrimestral" target="_blank" rel="noreferrer">Fonte FIP ↗</a> · <a href="https://dados.cvm.gov.br/dataset/fidc-doc-inf_mensal" target="_blank" rel="noreferrer">Fonte FIDC ↗</a></p><DataComponent id="quality-exclusions" queryId="quality" title="Ocorrências excluídas nesta competência e universo" sourceRows={audited} displayRows={audited}><DataTable rows={audited} columns={[col('id','CNPJ'),col('universe','Origem'),col('reason','Motivo')]} caption="Grupos excluídos"/></DataComponent></details>
 </div>
}
